<a href="https://colab.research.google.com/github/soutrik71/pytorch_classics/blob/main/AP_Torch1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np
print(torch.__version__)
print(torch.cuda.is_available())
# print(torch.cuda.device_count())
# print(torch.cuda.current_device())
# print(torch.cuda.get_device_name())
print(torch.cpu.device_count())

2.1.0+cu121
False
1


In [2]:
device = "cuda" if torch.cuda.is_available() else "cpu"
print(device)

cpu


##Initializing Tensors

In [7]:
# a scalar
my_scalar = torch.tensor(42, dtype = torch.float16, device=device)
print(my_scalar)

tensor(42., dtype=torch.float16)


In [8]:
# a Tensor in this case of shape 2x3
my_matrix = torch.tensor([[1,2,4],[11,22,44]], dtype = torch.float32, device = device)
print(my_matrix)

tensor([[ 1.,  2.,  4.],
        [11., 22., 44.]])


In [24]:
# few properties of a tensor
print(my_scalar.shape)
print(my_scalar.item())
print(my_matrix.shape)
print(my_matrix.dtype)
print(my_matrix.ndim)
print(my_matrix.numpy()) # convert into numpy
print(my_matrix.device)
print(my_matrix.numel()) # no of elements

torch.Size([])
42.0
torch.Size([2, 3])
torch.float32
2
[[ 1.  2.  4.]
 [11. 22. 44.]]
cpu
6


In [31]:
# Tensor
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]],
                      dtype = torch.half,
                      device = device)
print(TENSOR)
print(TENSOR.shape)
print(TENSOR.dtype)
print(TENSOR.size()) # same as shape attrb
print(TENSOR.ndim)
print(TENSOR.device)
print(TENSOR.numpy())
print(TENSOR.numel())

tensor([[[1., 2., 3.],
         [3., 6., 9.],
         [2., 4., 5.]]], dtype=torch.float16)
torch.Size([1, 3, 3])
torch.float16
torch.Size([1, 3, 3])
3
cpu
[[[1. 2. 3.]
  [3. 6. 9.]
  [2. 4. 5.]]]
9


In [21]:
TENSOR.shape

torch.Size([1, 3, 3])

##### View of a TENSOR
![picture](https://drive.google.com/uc?export=view&id=1-UGpr8PzhAhHW6U2cpSpGu3SWjVodhaJ)

##### Blank/Random tensor initalization methods

In [35]:
x = torch.empty(size=(3, 3))  # Tensor of shape 3x3 with uninitialized data
print(x)
x = torch.zeros((3, 3))  # Tensor of shape 3x3 with values of 0
print(x)
xx = torch.rand(
    (3, 3)
)  # Tensor of shape 3x3 with values from uniform distribution in interval [0,1)
print(xx)
x = torch.ones((3, 3))  # Tensor of shape 3x3 with values of 1
print(x)
x = torch.eye(5, 5)  # Returns Identity Matrix I, (I <-> Eye), matrix of shape 2x3
print(x)
x1x = torch.arange(
    start=0, end=5, step=1
)  # Tensor [0, 1, 2, 3, 4], note, can also do: torch.arange(5)
print(x1x)
x = torch.linspace(start=0.1, end=1, steps=10)  # x = [0.1, 0.2, ..., 1]
print(x)
x = torch.empty(size=(1, 5)).normal_(
    mean=0, std=1
)  # Normally distributed with mean=0, std=1
print(x)
x = torch.empty(size=(1, 5)).uniform_(
    0, 1
)  # Values from a uniform distribution low=0, high=1
print(x)
x = torch.diag(torch.ones(3))  # Diagonal matrix of shape 3x3
x = torch.zeros_like(xx)
print(x)

tensor([[1.7833e+28, 4.5247e-41, 3.5426e-26],
        [3.1273e-41, 1.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 6.7262e-44]])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[0.4314, 0.5542, 0.2598],
        [0.4405, 0.0880, 0.5806],
        [0.3250, 0.0118, 0.2295]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
tensor([0, 1, 2, 3, 4])
tensor([0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000, 0.9000,
        1.0000])
tensor([[-0.5552, -0.8960,  0.3334,  1.2243, -0.8040]])
tensor([[0.6607, 0.7109, 0.5522, 0.6534, 0.7031]])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


##### Datatypes Characteristics
The most common type (and generally the default) is torch.float32 or torch.float.

This is referred to as "32-bit floating point".

But there's also 16-bit floating point (torch.float16 or torch.half) and 64-bit floating point (torch.float64 or torch.double).

And to confuse things even more there's also 8-bit, 16-bit, 32-bit and 64-bit integers.

In [39]:
tensor = torch.arange(10)
print(tensor)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [46]:
print(tensor.dtype)
print(tensor.to(torch.int8))
print(tensor.half()) # float16
print(tensor.double()) # float64
print(tensor.short()) # int16
print(tensor.long()) # int64

torch.int64
tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int8)
tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=torch.float16)
tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=torch.float64)
tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int16)
tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


##Tensor Mathematical Operations

In [49]:
# declaring basic tensors--
x = torch.tensor([1,19,7],device = device).to(torch.float16)
y = torch.tensor([22,4,17],device = device).to(torch.float16)

In [50]:
z1 = torch.add(x, y)  # This is another way
z2 = x + y  # This is my preferred way, simple and clean.
print(z1,z2)

tensor([23., 23., 24.], dtype=torch.float16) tensor([23., 23., 24.], dtype=torch.float16)


In [51]:
# -- Inplace Operations --
t = torch.zeros(3)
t.add_(x)
print(t)

tensor([ 1., 19.,  7.])


In [55]:
# matrix multiplications -- all flavors
x = torch.tensor([[1, 2], [3, 4]])
y = torch.tensor([[5, 6], [7, 8]])
print(torch.mm(x, y))
print(x@y)
print(x.matmul(y))
print(torch.matmul(x,y))

tensor([[19, 22],
        [43, 50]])
tensor([[19, 22],
        [43, 50]])
tensor([[19, 22],
        [43, 50]])
tensor([[19, 22],
        [43, 50]])


In [61]:
# Shapes need to be in the right way
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]], dtype=torch.float32)

# torch.matmul(tensor_A, tensor_B) # (this will error)

In [62]:
torch.matmul(tensor_A, tensor_B.T)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

In [63]:
# element wise mul / dot product
print(tensor_A*tensor_B)

tensor([[ 7., 20.],
        [24., 44.],
        [45., 72.]])


In [66]:
# for dot product to work the tensors have to be 1D -- **
torch.dot(torch.tensor([2, 3]), torch.tensor([2, 1]))

tensor(7)