<a href="https://colab.research.google.com/github/soutrik71/pytorch_classics/blob/main/AP_Torch1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np
print(torch.__version__)
print(torch.cuda.is_available())
# print(torch.cuda.device_count())
# print(torch.cuda.current_device())
# print(torch.cuda.get_device_name())
print(torch.cpu.device_count())

2.1.0+cu121
False
1


In [2]:
device = "cuda" if torch.cuda.is_available() else "cpu"
print(device)

cpu


##Initializing Tensors

In [7]:
# a scalar
my_scalar = torch.tensor(42, dtype = torch.float16, device=device)
print(my_scalar)

tensor(42., dtype=torch.float16)


In [8]:
# a Tensor in this case of shape 2x3
my_matrix = torch.tensor([[1,2,4],[11,22,44]], dtype = torch.float32, device = device)
print(my_matrix)

tensor([[ 1.,  2.,  4.],
        [11., 22., 44.]])


In [24]:
# few properties of a tensor
print(my_scalar.shape)
print(my_scalar.item())
print(my_matrix.shape)
print(my_matrix.dtype)
print(my_matrix.ndim)
print(my_matrix.numpy()) # convert into numpy
print(my_matrix.device)
print(my_matrix.numel()) # no of elements

torch.Size([])
42.0
torch.Size([2, 3])
torch.float32
2
[[ 1.  2.  4.]
 [11. 22. 44.]]
cpu
6


In [31]:
# Tensor
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]],
                      dtype = torch.half,
                      device = device)
print(TENSOR)
print(TENSOR.shape)
print(TENSOR.dtype)
print(TENSOR.size()) # same as shape attrb
print(TENSOR.ndim)
print(TENSOR.device)
print(TENSOR.numpy())
print(TENSOR.numel())

tensor([[[1., 2., 3.],
         [3., 6., 9.],
         [2., 4., 5.]]], dtype=torch.float16)
torch.Size([1, 3, 3])
torch.float16
torch.Size([1, 3, 3])
3
cpu
[[[1. 2. 3.]
  [3. 6. 9.]
  [2. 4. 5.]]]
9


In [21]:
TENSOR.shape

torch.Size([1, 3, 3])

##### View of a TENSOR
![picture](https://drive.google.com/uc?export=view&id=1-UGpr8PzhAhHW6U2cpSpGu3SWjVodhaJ)

##### Blank/Random tensor initalization methods

In [35]:
x = torch.empty(size=(3, 3))  # Tensor of shape 3x3 with uninitialized data
print(x)
x = torch.zeros((3, 3))  # Tensor of shape 3x3 with values of 0
print(x)
xx = torch.rand(
    (3, 3)
)  # Tensor of shape 3x3 with values from uniform distribution in interval [0,1)
print(xx)
x = torch.ones((3, 3))  # Tensor of shape 3x3 with values of 1
print(x)
x = torch.eye(5, 5)  # Returns Identity Matrix I, (I <-> Eye), matrix of shape 2x3
print(x)
x1x = torch.arange(
    start=0, end=5, step=1
)  # Tensor [0, 1, 2, 3, 4], note, can also do: torch.arange(5)
print(x1x)
x = torch.linspace(start=0.1, end=1, steps=10)  # x = [0.1, 0.2, ..., 1]
print(x)
x = torch.empty(size=(1, 5)).normal_(
    mean=0, std=1
)  # Normally distributed with mean=0, std=1
print(x)
x = torch.empty(size=(1, 5)).uniform_(
    0, 1
)  # Values from a uniform distribution low=0, high=1
print(x)
x = torch.diag(torch.ones(3))  # Diagonal matrix of shape 3x3
x = torch.zeros_like(xx)
print(x)

tensor([[1.7833e+28, 4.5247e-41, 3.5426e-26],
        [3.1273e-41, 1.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 6.7262e-44]])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[0.4314, 0.5542, 0.2598],
        [0.4405, 0.0880, 0.5806],
        [0.3250, 0.0118, 0.2295]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
tensor([0, 1, 2, 3, 4])
tensor([0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000, 0.9000,
        1.0000])
tensor([[-0.5552, -0.8960,  0.3334,  1.2243, -0.8040]])
tensor([[0.6607, 0.7109, 0.5522, 0.6534, 0.7031]])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


##### Datatypes Characteristics
The most common type (and generally the default) is torch.float32 or torch.float.

This is referred to as "32-bit floating point".

But there's also 16-bit floating point (torch.float16 or torch.half) and 64-bit floating point (torch.float64 or torch.double).

And to confuse things even more there's also 8-bit, 16-bit, 32-bit and 64-bit integers.

In [39]:
tensor = torch.arange(10)
print(tensor)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [46]:
print(tensor.dtype)
print(tensor.to(torch.int8))
print(tensor.half()) # float16
print(tensor.double()) # float64
print(tensor.short()) # int16
print(tensor.long()) # int64

torch.int64
tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int8)
tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=torch.float16)
tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=torch.float64)
tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int16)
tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


##### Forms of a tensor
![picture](https://drive.google.com/uc?export=view&id=1dTT3vbHv9wep-5F85gztqm9Wf2PW_Xpe)

##Tensor Mathematical Operations

In [49]:
# declaring basic tensors--
x = torch.tensor([1,19,7],device = device).to(torch.float16)
y = torch.tensor([22,4,17],device = device).to(torch.float16)

In [50]:
z1 = torch.add(x, y)  # This is another way
z2 = x + y  # This is my preferred way, simple and clean.
print(z1,z2)

tensor([23., 23., 24.], dtype=torch.float16) tensor([23., 23., 24.], dtype=torch.float16)


In [51]:
# -- Inplace Operations --
t = torch.zeros(3)
t.add_(x)
print(t)

tensor([ 1., 19.,  7.])


##### Tensor multiplications

In [55]:
# matrix multiplications -- all flavors
x = torch.tensor([[1, 2], [3, 4]])
y = torch.tensor([[5, 6], [7, 8]])
print(torch.mm(x, y))
print(x@y)
print(x.matmul(y))
print(torch.matmul(x,y))

tensor([[19, 22],
        [43, 50]])
tensor([[19, 22],
        [43, 50]])
tensor([[19, 22],
        [43, 50]])
tensor([[19, 22],
        [43, 50]])


In [82]:
# Shapes need to be in the right way
tensor_A = torch.tensor([[1, 2],
                         [11, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]], dtype=torch.float32)

# torch.matmul(tensor_A, tensor_B) # (this will error)

In [62]:
torch.matmul(tensor_A, tensor_B.T)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

In [63]:
# element wise mul / dot product
print(tensor_A*tensor_B)

tensor([[ 7., 20.],
        [24., 44.],
        [45., 72.]])


In [66]:
# for dot product to work the tensors have to be 1D -- **
torch.dot(torch.tensor([2, 3]), torch.tensor([2, 1]))

tensor(7)

In [72]:
# -- Batch Matrix Multiplication --
batch = 32
n = 10
m = 20
p = 30
tensor1 = torch.rand((batch, n, m))
tensor2 = torch.rand((batch, m, p))
out_bmm = torch.bmm(tensor1, tensor2)
print(out_bmm.shape)# 32b*10r*30c
print(out_bmm[0].shape) # 10r*30c

torch.Size([32, 10, 30])
torch.Size([10, 30])


##### Aggregated operations

In [84]:
tensor_A

tensor([[ 1.,  2.],
        [11.,  4.],
        [ 5.,  6.]])

In [83]:
print(tensor_A.max())
print(tensor_A.max(dim=0)) # col wise
print(tensor_A.max(dim=1)) # row wise

tensor(11.)
torch.return_types.max(
values=tensor([11.,  6.]),
indices=tensor([1, 2]))
torch.return_types.max(
values=tensor([ 2., 11.,  6.]),
indices=tensor([1, 0, 1]))


In [85]:
print(tensor_A.mean())
print(tensor_A.mean(dim=0)) # col wise mean
print(tensor_A.mean(dim=1)) # row wise mean

tensor(4.8333)
tensor([5.6667, 4.0000])
tensor([1.5000, 7.5000, 5.5000])


In [86]:
# same using torch methods
values,indices = torch.max(tensor_A,dim=1)
print(values)
print(indices)

tensor([ 2., 11.,  6.])
tensor([1, 0, 1])


##### Tensor Broadcasting and Transpose

In [88]:
# -- Example of broadcasting --
x1 = torch.rand((5, 5))
x2 = torch.ones((1, 5))
z = (x1 * x2)
print(z)

tensor([[0.8236, 0.6348, 0.6086, 0.4746, 0.9416],
        [0.2919, 0.0121, 0.7253, 0.8745, 0.8874],
        [0.3885, 0.8592, 0.3542, 0.0349, 0.7945],
        [0.8605, 0.6092, 0.5573, 0.8594, 0.4344],
        [0.5308, 0.4412, 0.5120, 0.4734, 0.5581]])


In [92]:
# torch.transpose(input, dim0, dim1) - where input is the desired tensor to transpose and dim0 and dim1 are the dimensions to be swapped.
# print(x1@x2) # wont work
print(x1@torch.transpose(x2,0,1)) # (5*5)@(5*1)->5*1

tensor([[3.4832],
        [2.7912],
        [2.4312],
        [3.3208],
        [2.5154]])


In [100]:
tensor_1 = torch.linspace(1, 10, 10)
print(torch.argmax(tensor_1))
print(torch.argmin(tensor_1))

tensor(9)
tensor(0)


In [101]:
print(torch.clamp(tensor_1, min=0))
print(torch.clamp(tensor_1, min=0,max=8.71))
# All values < 0 set to 0 and values > 0 unchanged (this is exactly ReLU function)
# If you want to values over max_val to be clamped, do torch.clamp(x, min=min_val, max=max_val)

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])
tensor([1.0000, 2.0000, 3.0000, 4.0000, 5.0000, 6.0000, 7.0000, 8.0000, 8.7100,
        8.7100])


In [103]:
x = torch.tensor([1, 0, 1, 1, 1], dtype=torch.bool)  # True/False values
print(torch.any(x))  # will return True, can also do x.any() instead of torch.any(x)
print(torch.all(x))  # will return Fa

tensor(True)
tensor(False)


## Tensor Indexing

##### Basic index based filter

In [108]:
batch_size = 10
features = 25
x = torch.rand((batch_size, features))

In [109]:
# For example: Want to access third example in the batch and the first ten features
print(x[2,0:10])

tensor([0.8465, 0.6312, 0.9758, 0.8354, 0.9033, 0.3257, 0.7675, 0.8077, 0.1043,
        0.3522])


In [114]:
# get the 0 row 1 feat and 1 row and 3 feat
x = torch.rand((3, 5))
rows = torch.tensor([0,1])
cols = torch.tensor([1,3])
print(x[rows, cols])

tensor([0.2470, 0.9724])


In [121]:
# reversal
x[-1,-2:]

tensor([0.3637, 0.9633])

tensor([[0.4079, 0.2470, 0.5638, 0.7323, 0.3522],
        [0.0685, 0.4529, 0.8509, 0.9724, 0.2934],
        [0.5128, 0.6001, 0.9480, 0.3637, 0.9633]])

##### Conditional filtering

In [124]:
tensor_A = torch.tensor([[1, 2],
                         [11, 4],
                         [5, 6]], dtype=torch.float32)
print(tensor_A)

tensor([[ 1.,  2.],
        [11.,  4.],
        [ 5.,  6.]])


In [125]:
tensor_A[(tensor_A <2) | (tensor_A > 5)]

tensor([ 1., 11.,  6.])

In [127]:
# conditional operations
print(
    torch.where(tensor_A > 10, tensor_A, tensor_A * 2)
)
#unique values
print(torch.tensor([0, 0, 1, 2, 2, 3, 4]).unique())

tensor([[ 2.,  4.],
        [11.,  8.],
        [10., 12.]])
tensor([0, 1, 2, 3, 4])


In [173]:
# 3dim filtering
x = torch.arange(1, 19).reshape(2, 3, 3)
x, x.shape

(tensor([[[ 1,  2,  3],
          [ 4,  5,  6],
          [ 7,  8,  9]],
 
         [[10, 11, 12],
          [13, 14, 15],
          [16, 17, 18]]]),
 torch.Size([2, 3, 3]))

In [174]:
print(x[0])

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


In [178]:
print(x[0][0,0])
print(x[0,0,0])
print(x[:,0,0])

tensor(1)
tensor(1)
tensor([ 1, 10])


In [180]:
# Get all values of 0th & 1st dimensions but only index 1 of 2nd dimension
x[:, :, 1]

tensor([[ 2,  5,  8],
        [11, 14, 17]])

In [182]:
# get sepcific row and column combinations
print(x[:,1,:])
print(x[:,1,1])

tensor([[ 4,  5,  6],
        [13, 14, 15]])
tensor([ 5, 14])


## Reshaping, stacking, squeezing and unsqueezing

```md
| Method                      | One-line description                                                                                         |
|-----------------------------|--------------------------------------------------------------------------------------------------------------|
| torch.reshape(input, shape) | Reshapes input to shape (if compatible), can also use torch.Tensor.reshape().                                |
| Tensor.view(shape)          | Returns a view of the original tensor in a different shape but shares the same data as the original tensor.  |
| torch.stack(tensors, dim=0) | Concatenates a sequence of tensors along a new dimension (dim), all tensors must be same size.               |
| torch.squeeze(input)        | Squeezes input to remove all the dimenions with value 1.                                                     |
| torch.unsqueeze(input, dim) | Returns input with a dimension value of 1 added at dim.                                                      |
| torch.permute(input, dims)  | Returns a view of the original input with its dimensions permuted (rearranged) to dims.                      |


```

In [148]:
x = torch.arange(1., 12.)
print(x, x.shape)
print(id(x))

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.]) torch.Size([11])
138678347161472


In [166]:
x1 = torch.rand(2, 5)
x2 = torch.rand(2, 5)

##### reshaping

In [149]:
z = x.reshape(1,11)
print(z.shape)
print(id(z))

torch.Size([1, 11])
138678347159872


In [150]:
# Remember though, changing the view of a tensor with torch.view() really only creates a new view of the same tensor.-- optimized than reshape
k = x.view(1, 11)
print(k.shape)
print(id(k))

torch.Size([1, 11])
138678347168352


In [151]:
z[0,0] = 100
print(z)
print(x)

tensor([[100.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.]])
tensor([100.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.])


In [152]:
k[0,0] = 99
print(k)
print(x)

tensor([[99.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.]])
tensor([99.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])


In [167]:
# -1 means unrolling of dimensions
print(x1.reshape(-1))
print(x1.view(-1))

tensor([0.4066, 0.9608, 0.4022, 0.6919, 0.3242, 0.6369, 0.5851, 0.0498, 0.6936,
        0.2594])
tensor([0.4066, 0.9608, 0.4022, 0.6919, 0.3242, 0.6369, 0.5851, 0.0498, 0.6936,
        0.2594])


In [153]:
# look like under the hood reshape = view

##### stacking

In [160]:
print(x.shape)
print(torch.stack([x, x],dim=0).shape) # horizantal wise
print(torch.stack([x, x], dim=1).shape) # vertical wise

torch.Size([11])
torch.Size([2, 11])
torch.Size([11, 2])


In [165]:
print(torch.cat((x1, x2), dim=0).shape) # horizantal
print(torch.cat((x1, x2), dim=1).shape) # vertical

torch.Size([4, 5])
torch.Size([2, 10])


##### squeeze and unsqueeze

In [184]:
x = torch.arange(
    10
)  # Shape is [10], let's say we want to add an additional so we have 1x10
print(x.unsqueeze(0).shape)  # 1x10 one index at 0 dim
print(x.unsqueeze(1).shape)  # 10x1 one index at 1 dim

torch.Size([1, 10])
torch.Size([10, 1])


In [190]:
# Let's say we have x which is 1x1x10 and we want to remove a dim so we have 1x10
xn = torch.arange(10).unsqueeze(0).unsqueeze(1)

In [199]:
# follow the progression
print(xn.shape)
xn1 = xn.squeeze(0)
print(xn1.shape)
xn2 = xn1.squeeze(0)
print(xn2.shape)

torch.Size([1, 1, 10])
torch.Size([1, 10])
torch.Size([10])


## Additionals

##### Pytorch and numpy

In [205]:
# np array -> tensor -> np array
np_array = np.arange(10).reshape(2, 5)
print(np_array)

tens1 = torch.from_numpy(np_array)
print(tens1)

np_array1 = tens1.numpy()
print(np_array1)

[[0 1 2 3 4]
 [5 6 7 8 9]]
tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])
[[0 1 2 3 4]
 [5 6 7 8 9]]


##### Reproducability

In [210]:
import random

# # Set the random seed
RANDOM_SEED=42 # try changing this to different values and see what happens to the numbers below
torch.manual_seed(seed=RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

# Have to reset the seed every time a new rand() is called
# Without this, tensor_D would be different to tensor_C
torch.random.manual_seed(seed=RANDOM_SEED) # try commenting this line out and seeing what happens
random_tensor_D = torch.rand(3, 4)

print(f"Tensor C:\n{random_tensor_C}\n")
print(f"Tensor D:\n{random_tensor_D}\n")
print(f"Does Tensor C equal Tensor D? (anywhere)")
torch.equal(random_tensor_C, random_tensor_D)

Tensor C:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Tensor D:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Does Tensor C equal Tensor D? (anywhere)


True